language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell

script:
  - pwsh -c 'Install-Module Pester -Force -Scope CurrentUser; Invoke-Pester'